### ISSUE TITLE
Remove event IDs and User IDs from showing up in event modals

### ISSUE THREAD

**Issue by shecking** [We-Work-On-Master/hangout-client#33]
Currently, when a modal is shown for an event, event and user ids are currently displayed.

Ex. event.id:5e69227123bae69f2a0d0ce0

5e6bbfc0369028db39a3ad7f, 5e69353cd7db05a3e6a46f27.....

These should be removed from the displayed event.

**Comment by drewmccarron** [comment]
Completed this one. Just a note: I made a couple other updates to the Info modals while I was there, cleaning them up and polishing them. Ex:
- A new "Number of attendees: " row
- 'Date' and 'Time' are now displayed on one line as " (Time), (Date) " like an actual date.

These changes were applied to all three current handlebar templates, because the Info modal works the same on all of them.
